### PR TITLE
Bugfix/1335

### LINKED ISSUE #1326: [6.0 Specific]: - Video doesn't upload intermittently (thumbnail, placeholder doesn't appear) after conversion process gets completed.
Environment:- https://spruce.dlib.indiana.edu
Devices:- All Devices/Browsers

**Steps to Reproduce**

1. Launch URL on browser.e.g:- Chrome.
2. Login with valid credentials.
3. Create new item under any collection.
4. Upload any video and follow steps for uploading.
5. Observe conversion process appears and wait till conversion is completed.

Observe Video doesn't upload after conversion and no poster/thumbnail is displayed along with title.

Note:- Issue is not reproducible on mallorn.
2. Reproducibilty for this issue is 2/5. 

**Done looks like**
Video should upload properly after conversion process is completed.

Please refer attached screenshot for details:
failed_upload

### LINKED ISSUE #1335: Video fails to upload and error message is displayed if name of file contains Special character " L with stroke".
Environment:- https://spruce.dlib.indiana.edu
Devices:- All Devices/Browsers

**Steps to Reproduce**

1. Launch URL on browser.
2. Login with valid credentials.
3. Access any collection and create new item.
4. Upload audio "SHYWOŁVE - 09 Lost in Motion" where L is latin (L with stroke).

Observe error message on trying to upload video.

Note:- Video upload fails after conversion process on mallorn.

**Done looks like**

User should be able to ingest or upload video with special characters in name.

Please refer attached screenshot for details:-
mallorn_error

spruce_error

### PR DESCRIPTION
**Pull request by carrickr**
Fixes #1335 
Fixes #1326

Fix it on the upload page for 6.0.

### CODE REVIEW

File: app/controllers/master_files_controller.rb [hunk 1]
```diff
@@ -170,8 +170,12 @@ def create
           # Use the errors key to signal that it should be a red notice box rather
           # than the default
           flash[:error] = "The file you have uploaded is too large"
-          redirect_to :back
-          return
+          return redirect_to :back
+        end
+
+        unless file.filename.valid_encoding? && file.name.is_ascii?
+          flash[:error] = 'The file you has non ASCII characters in its name.'
```
Comment (cjcolvar) [inline app/controllers/master_files_controller.rb]: Is "The file you have uploaded has non-ASCII characters in its name.' not long?  That would make it consistent with the too large message.

**Comment by carrickr** [comment]
@cjcolvar text changed
