### PR TITLE
remove the batch file after

### LINKED ISSUE #2390: Batch ingest going into a loop and ingesting the same items multiple times
### Descriptive summary
Server: spruce.dlib.indiana.edu
Testing: Regression 
Browser: Chrome(61.0.3163.100 (64-bit))
Operating System: Windows10
Issue: Batch ingest going into a loop and ingesting the same items multiple times

### Steps to reproduce
1. Create a manifest file and start the batch ingest using it.
2. Keep checking the e-mail notifications and the ingest process in avalon.
3. Multiple mails will be coming saying that batch process is successful, and can observe the same item ingesting multiple times in the collection.

### PR DESCRIPTION
**Pull request by carrickr**
Fixes #2390

### CODE REVIEW

**Comment by cjcolvar** [comment]
This works for local filesystem, but I think we'll need to change this into a method on `Avalon::Batch::FileManifest` and `Avalon::Batch::S3Manifest` (maybe also `Avalon::Batch::Manifest`?).

**Comment by carrickr** [comment]
@cjcolvar I think we need to tag in @mbklein and maybe have a larger talk on this.  We have the issue of needing the AWS gem for Avalon on AWS builds, but what about people running on IBM's cloud, etc (and we have people doing that).  We need to talk pattern.  Is it up to individual institutions to just find and replace FileUtil with the proper RubyGem (AWS/IBM/etc) or what?

File: spec/lib/avalon/batch_ingest_spec.rb [hunk 1]
```diff
@@ -114,14 +119,16 @@
     end
 
     it 'should ingest batch with spaces in name' do
-      space_batch_path = File.join('spec/fixtures/dropbox/example batch ingest', 'batch manifest with spaces.xlsx')
+      FileUtils.cp_r 'spec/fixtures/dropbox/example batch ingest', @dropbox_dir
```
Comment (cjcolvar) [inline spec/lib/avalon/batch_ingest_spec.rb]: Do you need this change (and in the test below)?  I'd rather not create files during the tests since they don't always get cleaned up.
