### PR TITLE
Resolve derivative resolution to width/height

### LINKED ISSUE #1992: Migration is not setting ebucore:width and ebucore:height on derivatives
The migration is looking in the wrong place for width and height in the encoding datastream for derivatives.  Instead of trying to set width and height separatly it is possible to read the value of `//video/resolution` from the datastream and set it on the derivative using `.resolution`.

### PR DESCRIPTION
**Pull request by bkeese**
Fixes #1992 

Checks derivatives resolution and height/width for migration. Raise error if they both exist but do not match.

### CODE REVIEW

File: app/migration/fedora_migrate/derivative/encoding_datastream_mover.rb [hunk 1]
```diff
@@ -28,9 +28,16 @@ def migrate
...
+        resolution = present_or_nil(encodingProfile.xpath('//video/resolution').text)
+        res_width,res_height = resolution.present? resolution.split('x') : [nil,nil]
+        width = present_or_nil(encodingProfile.xpath('//video/resolution/width').text)
+        height = present_or_nil(encodingProfile.xpath('//video/resolution/height').text)
+        if (res_width.present? and width.present? and res_width!=width) or (res_height.present? and height.present? and res_height!=height)
+          raise FedoraMigrate::Errors::MigrationError, "Derivative resolution and height/width do not match" 
+        end
+        target.width = width || res_width
+        target.height = height || res_height
+        target.resolution = "#{target.width}x#{target.height}" if target.width.present? && target.height.present?
```
Comment (cjcolvar) [inline app/migration/fedora_migrate/derivative/encoding_datastream_mover.rb]: `.resolution` ends up setting `.width` and `.height` and vice versa so I don't think we need to call it as well.  You should be fine with lines 38-39 and skipping this one.
