### PR TITLE
Use #id instead of removed #pid

### LINKED ISSUE #1730: Playlist is hanging at the end of first video in the list, and not giving access to remaining items
### Descriptive summary
Server: spruce.dlib.indiana.edu
Testing: Regression
Browser: Chrome(56.0.2924.87 (64-bit))
Operating System: Windows10
Issue: If the playlist contains more than one item, I cannot access the items other than the first item in the list. And player is hanging at the end after playing the first item

### Steps to reproduce the behavior

1. Login to the spruce system
2. Add two items to a new playlist
3. Try to access the items other than first item (not accessible)
4. Play the first item, and wait until it reaches the end of the timeline (player hangs at this point)

### Related work

Link to related tickets or prior related work here.

### PR DESCRIPTION
**Pull request by cjcolvar**
Fixes #1730.

### CODE REVIEW

File: app/views/playlists/refresh_info.js.erb [hunk 1]
```diff
@@ -21,10 +21,10 @@ Unless required by applicable law or agreed to in writing, software distributed
 <% clip_start = @current_clip.start_time / 1000.0 %>
 <% clip_end = @current_clip.end_time / 1000.0 %>
 <% clip_frag = "?t=#{clip_start},#{clip_end}" %>
-<% link = pid_section_media_object_path(@current_mediaobject, @current_masterfile.pid) + clip_frag %>
+<% link = pid_section_media_object_path(@current_mediaobject, @current_masterfile.id) + clip_frag %>
```
Comment (bkeese) [inline app/views/playlists/refresh_info.js.erb]: I think this needs to be id_section_media_object_path

Comment (cjcolvar) [inline app/views/playlists/refresh_info.js.erb]: good catch
