### PR TITLE
Fix marker placement for dynamic page resize

### LINKED ISSUE #1541: Playlist Marker Icons Incorrectly Aligned to Offset
### Steps to reproduce
See the following public playlist: https://media.dlib.indiana.edu/playlists/859
 
You can see that when the 1st marker, close to the beginning of the playlist item, is selected, the carat lines up well with the scrubber, but when the last marker, near the end, is selected, it does not line up.

### Done Looks Like
Playlist marker icons are properly aligned to the correct visual position on the rail.

### Example Images
marker 1 selected

marker 5 selected

### PR DESCRIPTION
**Pull request by bkeese**
Fixes #1541 

Marker placement now adjusts for page resize.

### CODE REVIEW

File: app/assets/javascripts/marker.js.coffee [hunk 1]
```diff
@@ -57,9 +57,9 @@ timeCodeToSeconds = (hh_mm_ss) ->
   row.find('button[name="marker_edit_save"]').remove()
   row.find('button[name="delete_marker"]').show()
   row.find('button[name="marker_edit_cancel"]').remove()
-  offset_percent = if isNaN(parseFloat(offset)) then 0 else Math.min(1, offset / currentPlayer.media.duration)
-  offset = Math.round($('.mejs-time-total').width() * offset_percent)+'px'
-  $('.scrubber-marker[data-marker="'+id+'"]').css('left',offset).attr('title',title_val)
+  offset_percent = if isNaN(parseFloat(offset)) then 0 else Math.min(100,Math.round(100*offset / currentPlayer.media.duration))
+  marker_title = String(title_val).replace(/"/g, '&quot;')+' ['+start_input.val()+']'
```
Comment (cjcolvar) [inline app/assets/javascripts/marker.js.coffee]: Are there any other special characters that need to be converted here?

Comment (bkeese) [inline app/assets/javascripts/marker.js.coffee]: Nope.
