### PR TITLE
Fix rake:aws:create_presets not working

### LINKED ISSUE #4178: Rake task to create Elastic Transcoder presets is broken
It's adding 2 `nil` templates when reading from yml file.

In a Rails console
```
et = Avalon::ElasticTranscoder.instance
templates = et.read_templates(Rails.root.join("config/elastic_transcoder_presets.yml"))
```

### PR DESCRIPTION
**Pull request by phuongdh**
Fixes #4178
Removes the nil elements from templates array and added test cases to validate.

### CODE REVIEW

File: lib/avalon/elastic_transcoder.rb [hunk 1]
```diff
@@ -36,19 +36,18 @@ def create_preset(template)
...
         container_description = container == 'ts' ? 'hls' : container
         template.merge!(
           name: "avalon-#{format}-#{quality}-#{container_description}",
           description: "Avalon Media System: #{format}/#{quality}/#{container_description}",
           container: container
         )
-
         template
       end
+    temp.reject { |e| e.to_s.empty? }
```
Comment (phuongdh) [inline lib/avalon/elastic_transcoder.rb:50]:
```suggestion
      temp.reject { |e| e.to_s.empty? }
```

File: spec/lib/avalon/elastic_transcoder_spec.rb [hunk 2]
```diff
@@ -55,8 +55,14 @@
   end
 
   describe "#read_templates" do
-    it 'returns an array' do
-      expect(et.read_templates(Rails.root.join('config', 'elastic_transcoder_presets.yml')).length).to eq(12)
-    end
+    subject(:templates) {et.read_templates(Rails.root.join('config', 'elastic_transcoder_presets.yml'))}
```
Comment (phuongdh) [inline spec/lib/avalon/elastic_transcoder_spec.rb:58]:
```suggestion
    subject(:templates) { et.read_templates(Rails.root.join('config', 'elastic_transcoder_presets.yml')) }
```

File: Gemfile [hunk 3]
```diff
@@ -142,6 +142,7 @@ group :test do
   gem 'simplecov'
   gem 'webdrivers', '~> 3.0'
   gem 'webmock', '~> 3.5.1'
+  gem 'rspec-its'
```
Comment (phuongdh) [inline Gemfile:145]: This line should be moved to before `gem 'rspec-retry'`
